project_name: python_offers_sdk
package_name: python_offers_sdk.api_client
package_version: "0.1.0"
async_client: true
use_path_prefixes_for_title_model_names: true
support_multiple_content_types: true
field_constraints: true
# Optional: avoids _default error raising
allow_version_updates: true
