name: Test, Build and Publish SDK

on:
  release:
    types: [created]

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    environment: testpypi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: PythonSDK_offers
        run: poetry install

      - name: Run tests
        working-directory: PythonSDK_offers
        run: poetry run pytest

      - name: Build package
        working-directory: PythonSDK_offers
        run: poetry build

      - name: Publish to TestPyPI
        working-directory: PythonSDK_offers
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: poetry publish -r testpypi --build
